### ISSUE TITLE
Fix fatal on canonical views of non-fieldable entities

### ISSUE THREAD

**Issue by andriokha** [YCloudYUSA/y_lb#158]
Hi, thanks as always for all your work on the distro :heart:

There's a bit of code in `y_lb_page_attachments_alter()` that assumes it can call `hasField()` on the entity from any canonical entity view route: https://github.com/YCloudYUSA/y_lb/blob/110ba9f53b896dcf4c4d36e6f00d2ed96ddcddad/y_lb.module#L167-L174

This can lead to a *Call to undefined method* error on a canonical entity view for a non-fieldable entity.

**Comment by podarok** [comment]
@andriokha could you provide example of such situation from the disto or contrib/custom work you are working on?

**Comment by andriokha** [comment]
Sure, I think the mostly likely candidate for non-fieldable entities is config entities: I saw an issue when viewing a webform and I'd expect the same for any config entity that provides a canonical route.

Thanks again!
