### ISSUE TITLE
Carousel and Donate blocks don't match the Figma font styling

### ISSUE THREAD

**Issue by carolpettirossi** [YCloudYUSA/y_lb#201]
Carousel and Donate blocks don't match the styling from Figma.

**Carousel**
From figma: Size 32px / Line height 34px
Current: font-size: 50px; / line-height: 60px;

**Donate**
From figma: Size 48px  / Line height 54px
Current: font-size: 56px; / line-height: 65px;

![image (7)](https://github.com/YCloudYUSA/y_lb/assets/1932735/45c9aebc-a633-41d1-8145-a9f565d2cd7c)
![image (6)](https://github.com/YCloudYUSA/y_lb/assets/1932735/5ef3a1f7-8996-49c4-800b-60c9038a03df)
![image (5)](https://github.com/YCloudYUSA/y_lb/assets/1932735/e5da1cc6-0864-4a5f-a5d0-458a5275c4e4)
![image (4)](https://github.com/YCloudYUSA/y_lb/assets/1932735/986988c7-e547-46be-bfd5-c25706eb3f1b)

**Comment by oleh-rymar** [comment]
205

**Comment by oleh-rymar** [comment]
@carolpettirossi 
https://github.com/YCloudYUSA/y_lb/pull/205
Please, review.

**Comment by froboy** [comment]
These changes are resolved in the respective d.o projects:
- https://www.drupal.org/project/y_donate/issues/3438104
- https://www.drupal.org/project/lb_carousel/issues/3438099
