### ISSUE TITLE
Correct project names in module dependencies

### ISSUE THREAD

**Issue by andriokha** [YCloudYUSA/y_lb#56]
I recently went through an upgrade and noticed that _node revision delete_ wasn't enabled despite being a dependency. Tbh I don't know that this is the culprit, but I noticed that the dependencies aren't right in the `.info.yml` - they all have the project name as `drupal`. (I do it all the time myself, it's so hard when in composer it's `drupal/node_revision_delete`!)

https://github.com/YCloudYUSA/y_lb/blob/93c25fae9ff70b74cddbc7c67e1f5d9989fec445/y_lb.info.yml#L7-L15

Thanks!

**Comment by podarok** [comment]
It's all correct @andriokha 
See https://ds-docs.y.org/docs/wiki/dependencies-in-drupal-info.yml/

Let us know what issue you faced with?

**Comment by andriokha** [comment]
Thanks for your time @podarok!

> It's all correct @andriokha
> See https://ds-docs.y.org/docs/wiki/dependencies-in-drupal-info.yml/

Ah, that goes against my understanding of the `.info.yml` file dependencies. To quote d.o.:
> Dependencies on Drupal core or contrib modules should be namespaced in the format `{project}:{module}`, where `{project}` is the project name as it appears in the Drupal.org URL (e.g. drupal.org/project/paragraphs) and `{module}` is the module's machine name.

And the example they give
> ```yaml
> dependencies:
>  - drupal:link
>  - drupal:views
>  - paragraphs:paragraphs
>  - webform:webform (>=6.1.0)
>```

https://www.drupal.org/docs/develop/creating-modules/let-drupal-know-about-your-module-with-an-infoyml-file#s-complete-example

> Let us know what issue you faced with?

The original issue that made me look was that `node_revision_delete` wasn't enabling, but that's fixed by #60 as far as I can tell.

Thanks again!

**Comment by podarok** [comment]
> Thanks for your time @podarok!
> 
> > It's all correct @andriokha
> > See https://ds-docs.y.org/docs/wiki/dependencies-in-drupal-info.yml/
> 
> Ah, that goes against my understanding of the `.info.yml` file dependencies. To quote d.o.:
> > Dependencies on Drupal core or contrib modules should be namespaced in the format `{project}:{module}`, where `{project}` is the project name as it appears in the Drupal.org URL (e.g. drupal.org/project/paragraphs) and `{module}` is the module's machine name.
> 
> And the example they give
> > ```yaml
> > dependencies:
> >  - drupal:link
> >  - drupal:views
> >  - paragraphs:paragraphs
> >  - webform:webform (>=6.1.0)
> >```
> 
> https://www.drupal.org/docs/develop/creating-modules/let-drupal-know-about-your-module-with-an-infoyml-file#s-complete-example
> 
> > Let us know what issue you faced with?
> 
> The original issue that made me look was that `node_revision_delete` wasn't enabling, but that's fixed by #60 as far as I can tell.
> 
> Thanks again!

On drupal.org also people ;)
People make mistakes ;)

Thank YOU

**Comment by froboy** [comment]
@podarok I'm not sure I'm clear on the resolution here. Can #57 be closed or should the conflicts be resolved and it be updated?

**Comment by podarok** [comment]
Yes, this is incorrect

**Comment by andriokha** [comment]
I'm not sure it matters, but I can't find any corroboration that the first string should always be `drupal` (for one thing, it seems a bit redundant). As well as the quoted docs, if you look at eg. [`\Drupal\Core\Extension\Dependency::createFromString()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21Dependency.php/function/Dependency%3A%3AcreateFromString/10) which parses a dependency string, it extracts the first part as the _project_. In a unit test it has an example [using `paragraphs` as the project name](https://api.drupal.org/api/drupal/core%21tests%21Drupal%21Tests%21Core%21Extension%21DependencyTest.php/function/DependencyTest%3A%3AtestIsCompatible/10). You can also see there are many more examples in the wild of [`paragraphs:paragraphs`](https://git.drupalcode.org/search?group_id=2&repository_ref=&scope=blobs&search=paragraphs%3Aparagraphs+filename%3A*.info.yml&snippets=false) than [`drupal:paragraphs`](https://git.drupalcode.org/search?group_id=2&repository_ref=&scope=blobs&search=drupal%3Aparagraphs+filename%3A*.info.yml&snippets=false) (with at least 8 of the latter come from YMCA-WS). As I say I'm not sure where it might cause actual problems, but it does seem that the issue is valid :shrug: :)

**Comment by podarok** [comment]
@froboy as a resolution, just to ensure no confusion

https://github.com/YCloudYUSA/y_lb/issues/56#issuecomment-1601353995
Since I put this https://ds-docs.y.org/docs/wiki/dependencies-in-drupal-info.yml/ doc nothing really changed in composer repo on drupal.org

So following this document is a preferable way for us
